version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Zipping Lambda code..."
      - zip -r index.zip index.py
artifacts:
  files:
    - index.zip