version: 0.2

# This CodeBuild spec is executed by P2CodeBuildProject for the frontend.
# It copies the contents of the 'frontend/' directory from the source artifact 
# directly to the S3 website bucket root.
phases:
  install:
    commands:
      - echo "Starting frontend deployment sync..."
  
  build:
    commands:
      # FRONTEND_BUCKET_NAME is passed via environment variable from the CFN template
      - echo "Syncing contents of frontend/ to s3://$FRONTEND_BUCKET_NAME"
      # The '--delete' flag ensures old files are removed from the website bucket
      # --acl public-read is necessary for public web hosting
      - aws s3 sync frontend/ s3://$FRONTEND_BUCKET_NAME --delete --acl public-read

artifacts:
  # No artifacts are needed, as deployment happens directly via the build command
  discard-paths: all